name: Generate daily post

on:
  workflow_dispatch:
  schedule:
    # Run every day at 07:00 UTC (adjust if you want)
    - cron: "0 7 * * *"

permissions:
  contents: write

jobs:
  daily:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Ensures the file content/data/candidate_pool.json exists.
      # If it's missing (fresh runner or weekly job didn't commit), we run a quick harvest first.
      - name: Ensure candidate pool (quick harvest if missing)
        run: |
          set -euxo pipefail
          POOL="content/data/candidate_pool.json"
          if [ ! -s "$POOL" ]; then
            echo "[daily] No candidate pool found — running a quick harvest…"
            python -m app.main --harvest \
              --min-reviews 80 \
              --max-apps 1500 \
              --batch-size 20 \
              --wait-s 2.0
          else
            echo "[daily] Found $POOL"
          fi

      - name: Validate candidate pool exists
        run: |
          test -s content/data/candidate_pool.json || (echo "candidate_pool.json still missing after quick harvest" >&2; exit 1)

      - name: Generate daily post
        run: |
          python -m app.main --daily

      # Optional: commit any generated/updated files (posts, data, etc.)
      - name: Commit & push updates (if any)
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          if ! git diff --quiet; then
            git add -A
            git commit -m "chore(daily): update generated content [skip ci]"
            git push
          else
            echo "No changes to commit."
          fi
