name: pelican-build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"     # hourly
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -c "import pelican; print('Pelican version:', pelican.__version__)"

      - name: Ensure content exists (debug)
        run: |
          ls -la
          ls -la content || true

      - name: Build site with Pelican
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          pelican content -s publishconf.py -o output

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
