name: pelican-build

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 * * * *"     # run at the start of every hour (UTC)
  workflow_dispatch:

permissions:
  contents: write   # allow committing generated posts back to the repo
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      # needed for rebase before pushing

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          python -c "import pelican; print('Pelican version:', pelican.__version__)"

      - name: Ensure content exists (debug)
        run: |
          ls -la
          ls -la content || true

      - name: Generate hourly post
        run: python scripts/run_pipeline.py

      - name: 'Debug: list generated posts'
        run: |
          echo "Markdown files under content/:"
          find content -maxdepth 3 -type f -name "*.md" -print
          echo "Most recent post preview:"
          head -20 $(ls -t content/posts/*.md | head -1) || true

      - name: Commit & push generated posts (rebase-safe)
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Stage only generated files (if any)
          git add content/posts/*.md || true

          # If nothing staged, exit quietly
          if git diff --cached --quiet; then
            echo "No new posts to commit."
          else
            # Rebase on latest remote to avoid non-fast-forward errors
            git fetch origin main
            git pull --rebase origin main
            git commit -m "chore(posts): hourly post [skip ci]"
            git push origin HEAD:main
          fi

      - name: Build site with Pelican
        run: |
          export PYTHONPATH="$GITHUB_WORKSPACE"
          pelican content -s publishconf.py -o output

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./output

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
